// All visible English text. The Arabic dictionary (ar.ts) must have exactly the same shape.

const interests = [
  { value: "Off-Plan", label: "Off-Plan" },
  { value: "Ready / Luxury Property", label: "Ready / Luxury Property" },
  { value: "Rental / Leasing", label: "Rental / Leasing" },
  { value: "Land, Building or Hotel", label: "Land, Building or Hotel" },
  { value: "Investment Opportunity", label: "Investment Opportunity" },
  { value: "Selling My Property", label: "Selling My Property" },
  { value: "Something Else", label: "Something Else" },
];

export const en = {
  htmlLang: "en",
  dir: "ltr" as "ltr" | "rtl",
  meta: {
    siteTitle: "iFind | Finding Value. Building Trust.",
    titleTemplate: "%s | iFind",
    description: "iFind Real Estate LLC, Dubai. Off-plan, ready and luxury properties, rentals, land, buildings and hotels across the UAE.",
    ogLocale: "en_AE",
  },
  brand: "iFind",
  legalName: "iFind Real Estate LLC",
  tagline: "Finding Value. Building Trust.",
  taglineParts: ["Finding Value.", "Building Trust."],
  orn: "ORN: 45937",
  address: "Office No. 1810, Churchill Tower, Business Bay, Dubai, UAE",
  streetAddress: "Office No. 1810, Churchill Tower, Business Bay",
  common: {
    skip: "Skip to content",
    enquireNow: "Enquire Now",
    whatsappUs: "WhatsApp Us",
    contactUs: "Contact Us",
    call: "Call",
    callUs: "Call Us",
    whatsapp: "WhatsApp",
    chat: "Chat",
    learnMore: "Learn more",
    image: "Image",
    close: "Close",
  },
  wa: {
    general: "Hello iFind, I would like to make an enquiry.",
    service: "Hello iFind, I would like to know more about {title}.",
    person: "Hello, I would like to speak with {name}.",
  },
  nav: {
    services: "Services",
    developers: "Developers",
    investors: "Investors",
    about: "About Us",
    team: "Our Team",
    contact: "Contact Us",
    explore: "Explore",
    home: "iFind home",
    main: "Main",
    mobile: "Mobile",
    openMenu: "Open menu",
    closeMenu: "Close menu",
    switchLabel: "العربية",
    switchAria: "Switch to Arabic",
  },
  services: [
    { slug: "off-plan", title: "Off-Plan", short: "Early access to new launches from Dubai's leading developers, with clear guidance on payment plans and handover." },
    { slug: "ready-luxury", title: "Ready & Luxury", short: "Move-in-ready homes and prime luxury residences, from everyday apartments to signature villas and penthouses." },
    { slug: "rentals", title: "Rentals & Leasing", short: "Residential and commercial leasing for tenants and landlords, handled with clarity and discretion." },
    { slug: "land", title: "Land, Buildings & Hotels", short: "Single plots, multiple plots, joint ventures and complex deals across the UAE, including warehouses, buildings and hotels." },
  ],
  steps: [
    { title: "Consultation", text: "We listen first: your goals, budget, timeline and the kind of asset you have in mind." },
    { title: "Options", text: "A focused shortlist of opportunities that fit, with the numbers laid out honestly." },
    { title: "Negotiation", text: "We represent your interest in every conversation, from price to payment terms." },
    { title: "Closing", text: "Paperwork, transfers and registrations handled step by step until the deal is complete." },
  ],
  footer: {
    services: "Services",
    company: "Company",
    contact: "Contact",
    office: "(Office)",
    whatsapp: "WhatsApp",
    rights: "All rights reserved.",
    privacy: "Privacy Policy",
    terms: "Terms",
  },
  cta: { eyebrow: "iFind" },
  placeholder: {
    heroHome: "Hero: Dubai skyline at dusk",
    whyHome: "Why iFind: team or Dubai architecture",
    investorsHome: "Investors: city skyline or meeting",
    contactMap: "Map or office photo",
    featureImage: "{title}: feature image",
  },
  interests,
  chat: {
    label: "Chat with iFind",
    greeting: "Hello! How may I assist you today?",
    chatWithUs: "Chat with us",
    askName: "Wonderful. May I have your name, please?",
    askPhone: "Thank you, {name}. What is the best phone or WhatsApp number to reach you on?",
    thanks: "Thank you. One of our consultants will contact you shortly.",
    failed: "Sorry, that did not go through. Please check the number or message us on WhatsApp.",
    yourName: "Your name",
    yourPhone: "Phone / WhatsApp",
    openWhatsApp: "Chat on WhatsApp",
    closeChat: "Close chat",
    openChat: "Open chat",
    dismiss: "Dismiss",
    send: "Send",
  },
  form: {
    fullName: "Full name *",
    phone: "Phone / WhatsApp *",
    email: "Email (optional)",
    interest: "I am interested in...",
    message: "Tell us briefly what you are looking for",
    send: "Send Enquiry",
    sending: "Sending...",
    note: "By sending this form you agree to be contacted about your enquiry.",
    thankTitle: "Thank you.",
    thankText: "We have received your enquiry and one of our consultants will contact you shortly.",
    continueWhatsApp: "Continue on WhatsApp",
    error: "Something went wrong. Please try WhatsApp.",
  },
  team: {
    brn: "BRN",
    languages: "Languages",
  },
  people: {
    "abid-khan": { name: "Abid Khan", role: "Managing Director" },
    "farwa-khan": { name: "Farwa Khan", role: "Commercial Sales Manager" },
    "muzamal-hameed": { name: "Muzamal Hameed", role: "Sales Manager" },
    "ehtesham-nazir": { name: "Ehtesham Nazir", role: "Digital Marketing Manager" },
    "dario-linus": { name: "Dario Linus", role: "Property Consultant" },
    "ishtiaq-ahmed": { name: "Ishtiaq Ahmed", role: "Property Consultant – Secondary Market" },
    "waqar-shah": { name: "Waqar Shah", role: "Sales Consultant" },
    "fayyaz-khan": { name: "Fayyaz Khan", role: "Public Relations Officer (PRO)" },
    "essam-nabil": { name: "Essam Nabil", role: "Senior Sales Executive" },
  } as Record<string, { name: string; role: string }>,
  ceo: {
    first: "Avaid",
    last: "Lateef",
    full: "Avaid Lateef",
    honorific: "Mr.",
    title: "Founder & CEO",
    messageA:
      "With over 8 years of real estate experience in Dubai and internationally, Mr. Avaid Lateef leads iFind Real Estate LLC with a clear vision: to deliver personalized, high-value property solutions with excellence and integrity.",
    messageB:
      "His global perspective, deep market knowledge, and client-first approach have established the company as a trusted name in Dubai's real estate sector.",
    signatureLine: "Founder & CEO, iFind Real Estate LLC",
  },
  mdBio:
    "Abid Khan has 12+ years of sales experience, including 8 in Dubai real estate. With a BBA and hospitality background, he leads iFind Real Estate LLC with a focus on client satisfaction, smart investments, and trusted service.",
  developers: {
    names: {
      emaar: "Emaar",
      damac: "Damac",
      sobha: "Sobha",
      "dubai-properties": "Dubai Properties",
      azizi: "Azizi",
      binghatti: "Binghatti",
      danube: "Danube Properties",
      nshama: "Nshama",
      fakhruddin: "Fakhruddin Properties",
      "bt-properties": "BT Properties",
      bnw: "BNW Developments",
      reportage: "Reportage",
    } as Record<string, string>,
    logo: "{name} logo",
    pageTitle: "Our Developer Partners",
    pageDescription: "iFind Real Estate is registered with Dubai's major developers, including Emaar, Damac, Sobha, Dubai Properties, Azizi, Binghatti and Danube.",
    eyebrow: "Developers",
    intro: "We are registered with the major developers in Dubai, giving our clients direct access to new launches and inventory.",
    count: "{n} developers",
    homeTitle: "Registered with Dubai's leading developers",
    viewAll: "View All Developers",
  },
  home: {
    eyebrow: "Dubai, United Arab Emirates",
    keywords: ["Off-Plan", "Ready", "Luxury", "Rentals", "Land", "Buildings", "Hotels"],
    servicesEyebrow: "Our Services",
    servicesTitle: "Every kind of property deal, in one place",
    servicesText: "We help you buy, sell and lease, from a first apartment to a hotel.",
    whyEyebrow: "Why iFind",
    whyTitle: "Built on trust, driven by value",
    why: [
      { title: "Licensed Brokers", text: "Every consultant is a registered broker, with their BRN shown openly on our Team page." },
      { title: "Honest Advice", text: "We tell you what is worth your money, and what is not, even when it costs us a deal." },
      { title: "UAE and Beyond", text: "Access across the UAE, with the ability to discuss opportunities outside it." },
      { title: "Complex Deals", text: "Experience with plots, joint ventures, buildings, hotels and warehouses." },
    ],
    investorsEyebrow: "Investor Services",
    investorsTitle: "Opportunities for serious investors",
    investorsText:
      "Local and international investors rely on us to identify opportunities, evaluate them honestly and close the deal, whether that is a single unit, a plot or a whole building.",
    investorsButton: "Investor Services",
    processEyebrow: "Our Process",
    processTitle: "Clear steps. No surprises.",
    teamEyebrow: "Our Team",
    teamTitle: "The people behind iFind",
    teamButton: "Meet the Team",
    alt: {
      hero: "Luxury waterfront villa with a pool at sunset",
      why: "Luxury interior with a glass and marble staircase",
      investors: "Dubai skyline and the Burj Khalifa at sunset",
    },
  },
  about: {
    pageTitle: "About Us",
    pageDescription:
      "About iFind Real Estate LLC, a Dubai brokerage helping clients buy, sell and lease property across the UAE. Meet our Founder & CEO Avaid Lateef, our Managing Director, vision, mission and values.",
    heroEyebrow: "iFind Real Estate LLC · Dubai",
    heroH1a: "About",
    heroH1b: "Us",
    lede: "Specializing in mid-range to luxury properties, our multinational team brings a global perspective and deep local expertise to every transaction.",
    stats: [
      { value: "8+", label: "Years of founder experience in Dubai and international real estate" },
      { value: "{team}", label: "Team members" },
      { value: "{dev}", label: "Developers we are registered with" },
    ],
    whoEyebrow: "Who We Are",
    whoTitle: "A Dubai brokerage built on honest advice",
    intro: [
      "At iFind Real Estate LLC, we are passionate about helping you find the perfect property and investment opportunities in the vibrant city of Dubai. Specializing in mid-range to luxury properties, our multinational team brings a global perspective and deep local expertise to every transaction.",
      "Founded by real estate expert Mr. Avaid Lateef, with over 8 years of industry experience, we have built a reputation for integrity, excellence, and personalized service. Whether you are buying your dream home, selling a prime property, or looking for sound investment opportunities, we are committed to making your real estate journey smooth, rewarding, and hassle-free.",
      "Our services span residential sales, commercial property brokerage, investment advisory, and prime land sourcing. With access to the city's most prestigious locations, we help you unlock the best opportunities in one of the world's safest and fastest-growing markets.",
      "At iFind, your success is our priority. We don't just find you a property. We help you build a prosperous future.",
    ],
    mdButton: "Meet the Full Team",
    purposeEyebrow: "Purpose",
    purposeTitle: "Our vision and mission",
    visionLabel: "Our Vision",
    missionLabel: "Our Mission",
    vision: "To be the real estate advisor people in the UAE and beyond trust first, known for honest advice and lasting relationships.",
    mission: "To help our clients buy, sell and lease property with clarity, integrity and expert guidance, from the first consultation to the day the deal closes.",
    valuesEyebrow: "What We Stand For",
    valuesTitle: "Our values",
    values: [
      { title: "Integrity", text: "We say what is true, even when it is not what you hoped to hear." },
      { title: "Value", text: "Every recommendation is measured against what it is genuinely worth to you." },
      { title: "Clarity", text: "Prices, fees and terms laid out plainly, with no surprises later." },
      { title: "Service", text: "Responsive, respectful and available when you need us." },
      { title: "Expertise", text: "Registered brokers with real knowledge of the Dubai and UAE market." },
    ],
    doEyebrow: "What We Do",
    doTitle: "Buy. Sell. Lease.",
  },
  teamPage: {
    title: "Our Team",
    description: "Meet the iFind Real Estate LLC team in Dubai: our Managing Director, directors, managers and property specialists.",
    eyebrow: "Our Team",
    h1: "The people behind iFind",
    lede: "A multinational team with a global perspective and deep local expertise, committed to personalised, honest service on every deal.",
    leadership: "Leadership",
    specialists: "Specialists & Support",
    readMore: "Read More",
  },
  contact: {
    title: "Contact Us",
    description: "Speak with iFind Real Estate LLC in Dubai about off-plan, ready, luxury, rentals, land, buildings and hotels.",
    eyebrow: "Contact Us",
    h1: "Let’s talk.",
    lede: "Tell us what you are looking for. A registered consultant will get back to you shortly.",
    mobile: "Mobile / WhatsApp",
    landline: "Office Landline",
    whatsapp: "WhatsApp",
    whatsappLink: "Message us on WhatsApp",
    email: "Email",
    office: "Office",
    formTitle: "Send an enquiry",
    mapTitle: "iFind Real Estate office location on Google Maps",
    openMap: "Open in Google Maps",
  },
  servicePage: {
    whatWeDo: "What we do",
    howWeHelp: "How we help",
    ourService: "Our service",
    process: "Process",
    processTitle: "From first call to closing",
  },
  servicePages: {
    offPlan: {
      metaTitle: "Off-Plan Properties in Dubai",
      metaDescription: "Early access to off-plan launches from Dubai's leading developers, with clear guidance on payment plans and handover.",
      eyebrow: "Off-Plan",
      title: "Off-Plan Properties",
      intro: "Early access to new launches from Dubai's established developers, explained clearly before you commit.",
      imageLabel: "Off-plan hero: Dubai skyline with new developments",
      sectionTitle: "Buy early, with clear eyes",
      sectionText:
        "Off-plan can offer attractive entry points, but every project has its own payment plan, timeline and risk profile. We help you compare launches side by side and understand exactly what you are signing.",
      offers: [
        { title: "Launch Access", text: "Information on new and upcoming launches from the developers we are registered with." },
        { title: "Payment Plan Review", text: "A plain-language breakdown of instalments, milestones and handover terms." },
        { title: "Project Comparison", text: "Location, developer track record, unit mix and specification compared fairly." },
        { title: "Unit Selection", text: "Help choosing the right unit, floor and view for your goal, whether living or investing." },
        { title: "Resale and Assignment", text: "Guidance if you want to sell an off-plan unit before handover." },
        { title: "Documentation", text: "Support through reservation, SPA and registration, step by step." },
      ],
      closing: null as null | { title: string; text: string },
    },
    readyLuxury: {
      metaTitle: "Ready & Luxury Properties in Dubai",
      metaDescription: "Move-in-ready homes and prime luxury residences across Dubai: apartments, villas, townhouses and penthouses.",
      eyebrow: "Ready & Luxury",
      title: "Ready & Luxury Properties",
      intro: "From well-priced everyday homes to signature residences in Dubai's most sought-after addresses.",
      imageLabel: "Luxury hero: premium villa or penthouse interior",
      sectionTitle: "Find the right home, at the right value",
      sectionText:
        "Whether you want a practical apartment or a landmark penthouse, we work from your brief and show you what is genuinely worth your attention, not simply what is available.",
      offers: [
        { title: "Apartments", text: "Studios to multi-bedroom residences across Dubai's established and emerging communities." },
        { title: "Villas and Townhouses", text: "Family homes with space, privacy and strong community amenities." },
        { title: "Luxury Residences", text: "Prime penthouses, branded residences and waterfront homes at the top end of the market." },
        { title: "Private Viewings", text: "Scheduled around you, with honest feedback on each property." },
        { title: "Price Guidance", text: "Comparable-based advice so you buy and sell with confidence." },
        { title: "Selling Your Property", text: "Positioning, pricing and presentation to reach serious buyers." },
      ],
      closing: null as null | { title: string; text: string },
    },
    rentals: {
      metaTitle: "Rentals & Leasing in Dubai",
      metaDescription: "Residential and commercial leasing for tenants and landlords in Dubai and across the UAE.",
      eyebrow: "Rentals & Leasing",
      title: "Rentals & Leasing",
      intro: "Residential and commercial leasing for tenants and landlords, handled with clarity and discretion.",
      imageLabel: "Rentals hero: bright modern apartment interior",
      sectionTitle: "The right tenant. The right place.",
      sectionText:
        "We connect landlords with reliable tenants and tenants with properties that suit their needs and budget, and we keep the process straightforward from viewing to signing.",
      offers: [
        { title: "For Tenants", text: "A focused shortlist matched to your budget, location and lifestyle." },
        { title: "For Landlords", text: "Marketing, viewings and tenant screening to place your property well." },
        { title: "Commercial Leasing", text: "Offices, retail units, warehouses and other commercial spaces." },
        { title: "Rental Guidance", text: "Realistic rent expectations based on current comparable listings." },
        { title: "Tenancy Paperwork", text: "Support with contracts and registration so everything is in order." },
        { title: "Long and Short Term", text: "Options to suit different lease lengths and requirements." },
      ],
      closing: null as null | { title: string; text: string },
    },
    land: {
      metaTitle: "Land, Buildings & Hotels in the UAE",
      metaDescription: "Buy and sell plots, enter joint ventures and complete complex deals across the UAE, including warehouses, buildings and hotels.",
      eyebrow: "Land, Buildings & Hotels",
      title: "Land, Buildings & Hotels",
      intro: "Plots, joint ventures and complex commercial deals across the UAE, including opportunities beyond it.",
      imageLabel: "Land hero: aerial view of plots or development site",
      sectionTitle: "Complex deals, handled with experience",
      sectionText:
        "Land and large assets need careful structuring. We work on single plots and multiple plots, joint ventures, and transactions involving warehouses, buildings and hotels. We source, evaluate and negotiate on your behalf.",
      offers: [
        { title: "Plot Sales and Purchases", text: "Residential, commercial and mixed-use land across the UAE." },
        { title: "Multiple Plots", text: "Assembling or selling several plots together as a single transaction." },
        { title: "Joint Ventures", text: "Introductions and deal structuring between landowners and developers." },
        { title: "Buildings", text: "Whole-building acquisitions and sales for investors and end users." },
        { title: "Hotels and Hospitality", text: "Hotel and hospitality assets for qualified buyers and sellers." },
        { title: "Warehouses", text: "Industrial and logistics properties for sale or lease." },
      ],
      closing: {
        title: "Looking outside the UAE?",
        text: "We can also discuss land opportunities beyond the UAE. Tell us what you are looking for and we will let you know honestly what we can do.",
      } as null | { title: string; text: string },
    },
    investors: {
      metaTitle: "Investor Services",
      metaDescription: "Investment opportunities in Dubai and the UAE for local and international investors: off-plan, ready, land, buildings and hotels.",
      eyebrow: "Investor Services",
      title: "Investor Services",
      intro: "Finding, evaluating and closing real estate investments in Dubai and across the UAE, for local and international investors.",
      imageLabel: "Investors hero: Dubai financial district at night",
      sectionTitle: "Invest with clarity, not guesswork",
      sectionText:
        "We help you identify opportunities that match your capital and goals, explain the numbers plainly, and carry the deal through to completion. We do not promise returns. We give you the facts so you can decide.",
      offers: [
        { title: "Opportunity Sourcing", text: "Off-plan, ready, land and commercial opportunities matched to your brief." },
        { title: "Market Briefing", text: "Honest context on areas, pricing and demand before you commit." },
        { title: "Deal Evaluation", text: "Costs, fees, payment terms and exit options laid out clearly." },
        { title: "Large and Complex Deals", text: "Multiple plots, joint ventures, buildings, warehouses and hotels." },
        { title: "International Investors", text: "Remote-friendly communication and guidance on the buying process in the UAE." },
        { title: "Selling and Leasing", text: "Support when you want to sell or lease an asset you already own." },
      ],
      closing: null as null | { title: string; text: string },
    },
  },
  legal: {
    eyebrow: "Legal",
    privacyTitle: "Privacy Policy",
    termsTitle: "Terms of Use",
    placeholder: "This page is a placeholder. The final {doc} for {company} will be published here.",
  },
};

export type Dict = typeof en;
