// All visible English text. The Arabic dictionary (ar.ts) must have exactly the same shape.

const interests = [
  { value: "Off-Plan", label: "Off-Plan" },
  { value: "Ready / Luxury Property", label: "Ready / Luxury Property" },
  { value: "Rental / Leasing", label: "Rental / Leasing" },
  { value: "Land, Building or Hotel", label: "Land, Building or Hotel" },
  { value: "Investment Opportunity", label: "Investment Opportunity" },
  { value: "Selling My Property", label: "Selling My Property" },
  { value: "Something Else", label: "Something Else" },
];

export const en = {
  htmlLang: "en",
  dir: "ltr" as "ltr" | "rtl",
  meta: {
    siteTitle: "iFind | Finding Value. Building Trust.",
    titleTemplate: "%s | iFind",
    description: "iFind Real Estate LLC, Dubai. Off-plan, ready and luxury properties, rentals, land, buildings and hotels across the UAE.",
    ogLocale: "en_AE",
  },
  brand: "iFind",
  legalName: "iFind Real Estate LLC",
  tagline: "Finding Value. Building Trust.",
  taglineParts: ["Finding Value.", "Building Trust."],
  orn: "ORN: 45937",
  address: "Office No. 1810, Churchill Tower, Business Bay, Dubai, UAE",
  streetAddress: "Office No. 1810, Churchill Tower, Business Bay",
  common: {
    skip: "Skip to content",
    enquireNow: "Enquire Now",
    whatsappUs: "WhatsApp Us",
    contactUs: "Contact Us",
    call: "Call",
    callUs: "Call Us",
    whatsapp: "WhatsApp",
    chat: "Chat",
    learnMore: "Learn more",
    image: "Image",
    close: "Close",
  },
  wa: {
    general: "Hello iFind, I would like to make an enquiry.",
    service: "Hello iFind, I would like to know more about {title}.",
    person: "Hello, I would like to speak with {name}.",
  },
  nav: {
    services: "Services",
    developers: "Developers",
    investors: "Investors",
    about: "About Us",
    team: "Our Team",
    contact: "Contact Us",
    careers: "Careers",
    explore: "Explore",
    home: "iFind home",
    main: "Main",
    mobile: "Mobile",
    openMenu: "Open menu",
    closeMenu: "Close menu",
    switchLabel: "العربية",
    switchAria: "Switch to Arabic",
  },
  services: [
    { slug: "off-plan", title: "Off-Plan", short: "Early access to new launches from Dubai's leading developers, with clear guidance on payment plans and handover." },
    { slug: "ready-luxury", title: "Ready & Luxury", short: "Move-in-ready homes and prime luxury residences, from everyday apartments to signature villas and penthouses." },
    { slug: "rentals", title: "Rentals & Leasing", short: "Residential and commercial leasing for tenants and landlords, handled with clarity and discretion." },
    { slug: "land", title: "Land, Buildings & Hotels", short: "Single plots, multiple plots, joint ventures and complex deals across the UAE, including warehouses, buildings and hotels." },
  ],
  steps: [
    { title: "Consultation", text: "We listen first: your goals, budget, timeline and the kind of asset you have in mind." },
    { title: "Options", text: "A focused shortlist of opportunities that fit, with the numbers laid out honestly." },
    { title: "Negotiation", text: "We represent your interest in every conversation, from price to payment terms." },
    { title: "Closing", text: "Paperwork, transfers and registrations handled step by step until the deal is complete." },
  ],
  footer: {
    services: "Services",
    company: "Company",
    contact: "Contact",
    office: "(Office)",
    whatsapp: "WhatsApp",
    rights: "All rights reserved.",
    privacy: "Privacy Policy",
    terms: "Terms",
  },
  cta: { eyebrow: "iFind" },
  placeholder: {
    heroHome: "Hero: Dubai skyline at dusk",
    whyHome: "Why iFind: team or Dubai architecture",
    investorsHome: "Investors: city skyline or meeting",
    contactMap: "Map or office photo",
    featureImage: "{title}: feature image",
  },
  interests,
  chat: {
    label: "Chat with iFind",
    greeting: "Hello! How may I assist you today?",
    chatWithUs: "Chat with us",
    askName: "Wonderful. May I have your name, please?",
    askPhone: "Thank you, {name}. What is the best phone or WhatsApp number to reach you on?",
    thanks: "Thank you. One of our consultants will contact you shortly.",
    failed: "Sorry, that did not go through. Please check the number or message us on WhatsApp.",
    yourName: "Your name",
    yourPhone: "Phone / WhatsApp",
    openWhatsApp: "Chat on WhatsApp",
    closeChat: "Close chat",
    openChat: "Open chat",
    dismiss: "Dismiss",
    send: "Send",
  },
  form: {
    fullName: "Full name *",
    phone: "Phone / WhatsApp *",
    email: "Email (optional)",
    interest: "I am interested in...",
    message: "Tell us briefly what you are looking for",
    send: "Send Enquiry",
    sending: "Sending...",
    note: "By sending this form you agree to be contacted about your enquiry.",
    thankTitle: "Thank you.",
    thankText: "We have received your enquiry and one of our consultants will contact you shortly.",
    continueWhatsApp: "Continue on WhatsApp",
    error: "Something went wrong. Please try WhatsApp.",
  },
  team: {
    brn: "BRN",
    languages: "Languages",
    languageNames: { English: "English", Urdu: "Urdu", Hindi: "Hindi", Punjabi: "Punjabi", Pashtu: "Pashto", Arabic: "Arabic" } as Record<string, string>,
    profile: {
      breadcrumb: "Our Team",
      mobile: "Direct line",
      email: "Email",
      callName: "Call {name}",
      whatsappName: "WhatsApp {name}",
      back: "Back to the team",
      about: "About {name}",
      metaTitle: "{name}, {role} | iFind Real Estate Dubai",
      metaDescription: "{name} is {role} at iFind Real Estate LLC, Dubai. Speak with {name} about off-plan, ready and luxury property, rentals, land, buildings and hotels in the UAE.",
      photoAlt: "{name}, {role} at iFind Real Estate",
    },
    bios: {} as Record<string, string>, // to be supplied by the company, one profile at a time
  },
  people: {
    "abid-khan": { name: "Abid Khan", role: "Managing Director" },
    "farwa-khan": { name: "Farwa Khan", role: "Commercial Sales Manager" },
    "muzamal-hameed": { name: "Muzamal Hameed", role: "Sales Manager" },
    "ehtesham-nazir": { name: "Ehtesham Nazir", role: "Digital Marketing Manager" },
    "dario-ceglia": { name: "Dario Ceglia", role: "Real Estate Consultant" },
    "ishtiaq-ahmed": { name: "Ishtiaq Ahmed", role: "Real Estate Consultant" },
    "shah-waqar": { name: "Shah Waqar", role: "Real Estate Consultant" },
    "fayyaz-khan": { name: "Fayyaz Khan", role: "Public Relations Officer (PRO)" },
    "essam-nabil": { name: "Essam Nabil", role: "Real Estate Consultant" },
  } as Record<string, { name: string; role: string }>,
  ceo: {
    first: "Avaid",
    last: "Lateef",
    full: "Avaid Lateef",
    honorific: "Mr.",
    title: "Founder & CEO",
    messageA:
      "With over 8 years of real estate experience in Dubai and internationally, Mr. Avaid Lateef leads iFind Real Estate LLC with a clear vision: to deliver personalized, high-value property solutions with excellence and integrity.",
    messageB:
      "His global perspective, deep market knowledge, and client-first approach have established the company as a trusted name in Dubai's real estate sector.",
    signatureLine: "Founder & CEO, iFind Real Estate LLC",
  },
  mdBio:
    "Abid Khan has 12+ years of sales experience, including 8 in Dubai real estate. With a BBA and hospitality background, he leads iFind Real Estate LLC with a focus on client satisfaction, smart investments, and trusted service.",
  developers: {
    names: {
      emaar: "Emaar",
      damac: "Damac",
      sobha: "Sobha",
      "dubai-properties": "Dubai Properties",
      azizi: "Azizi",
      binghatti: "Binghatti",
      danube: "Danube Properties",
      nshama: "Nshama",
      fakhruddin: "Fakhruddin Properties",
      "bt-properties": "BT Properties",
      bnw: "BNW Developments",
      reportage: "Reportage",
    } as Record<string, string>,
    logo: "{name} logo",
    visit: "Visit the official {name} website",
    pageTitle: "Our Developer Partners",
    pageDescription: "iFind Real Estate is registered with Dubai's major developers, including Emaar, Damac, Sobha, Dubai Properties, Azizi, Binghatti and Danube.",
    eyebrow: "Developers",
    intro: "We are registered with the major developers in Dubai, giving our clients direct access to new launches and inventory.",
    count: "{n} developers",
    homeTitle: "Registered with Dubai's leading developers",
    viewAll: "View All Developers",
  },
  home: {
    eyebrow: "Dubai, United Arab Emirates",
    keywords: ["Off-Plan", "Ready", "Luxury", "Rentals", "Land", "Buildings", "Hotels"],
    servicesEyebrow: "Our Services",
    servicesTitle: "Every kind of property deal, in one place",
    servicesText: "We help you buy, sell and lease, from a first apartment to a hotel.",
    whyEyebrow: "Why iFind",
    whyTitle: "Built on trust, driven by value",
    why: [
      { title: "Licensed Brokers", text: "Every consultant is a registered broker, with their BRN shown openly on our Team page." },
      { title: "Honest Advice", text: "We tell you what is worth your money, and what is not, even when it costs us a deal." },
      { title: "UAE and Beyond", text: "Access across the UAE, with the ability to discuss opportunities outside it." },
      { title: "Complex Deals", text: "Experience with plots, joint ventures, buildings, hotels and warehouses." },
    ],
    investorsEyebrow: "Investor Services",
    investorsTitle: "Opportunities for serious investors",
    investorsText:
      "Local and international investors rely on us to identify opportunities, evaluate them honestly and close the deal, whether that is a single unit, a plot or a whole building.",
    investorsButton: "Investor Services",
    processEyebrow: "Our Process",
    processTitle: "Clear steps. No surprises.",
    teamEyebrow: "Our Team",
    teamTitle: "The people behind iFind",
    teamButton: "Meet the Team",
    alt: {
      hero: "Aerial view of Dubai skyscrapers",
      why: "Luxury interior with a glass and marble staircase",
      investors: "Dubai skyline and the Burj Khalifa at sunset",
    },
  },
  about: {
    pageTitle: "About Us",
    pageDescription:
      "About iFind Real Estate LLC, a Dubai brokerage helping clients buy, sell and lease property across the UAE. Meet our Founder & CEO Avaid Lateef, our Managing Director, vision, mission and values.",
    heroEyebrow: "iFind Real Estate LLC · Dubai",
    heroH1a: "About",
    heroH1b: "Us",
    lede: "Specializing in mid-range to luxury properties, our multinational team brings a global perspective and deep local expertise to every transaction.",
    stats: [
      { value: "8+", label: "Years of founder experience in Dubai and international real estate" },
      { value: "{team}", label: "Team members" },
      { value: "{dev}", label: "Developers we are registered with" },
    ],
    whoEyebrow: "Who We Are",
    whoTitle: "A Dubai brokerage built on honest advice",
    intro: [
      "At iFind Real Estate LLC, we are passionate about helping you find the perfect property and investment opportunities in the vibrant city of Dubai. Specializing in mid-range to luxury properties, our multinational team brings a global perspective and deep local expertise to every transaction.",
      "Founded by real estate expert Mr. Avaid Lateef, with over 8 years of industry experience, we have built a reputation for integrity, excellence, and personalized service. Whether you are buying your dream home, selling a prime property, or looking for sound investment opportunities, we are committed to making your real estate journey smooth, rewarding, and hassle-free.",
      "Our services span residential sales, commercial property brokerage, investment advisory, and prime land sourcing. With access to the city's most prestigious locations, we help you unlock the best opportunities in one of the world's safest and fastest-growing markets.",
      "At iFind, your success is our priority. We don't just find you a property. We help you build a prosperous future.",
    ],
    mdButton: "Meet the Full Team",
    mdProfile: "About the Managing Director",
    purposeEyebrow: "Purpose",
    visionLabel: "Our Vision",
    missionLabel: "Our Mission",
    visionText: [
      "At iFind Real Estate, our vision is to make real estate simpler, smarter, and more transparent — especially where transactions become complex.",
      "From prime land and large-scale development opportunities to commercial assets, ultra-luxury properties, off-plan investments, and the wider residential market, we aim to connect the right people with the right opportunities across every segment of Dubai real estate.",
      "We specialize in navigating transactions that require more than traditional brokerage — bringing together landowners, investors, developers, institutions, and end users, while simplifying negotiations, structuring opportunities, and helping move complex deals from possibility to completion.",
      "Our ambition is to build a real estate company known not simply for closing transactions, but for solving challenges, uncovering opportunities, creating long-term value, and earning trust at every stage.",
    ],
    missionText: [
      "At iFind Real Estate, our mission is to build a real estate company where our word is our reputation.",
      "We want the name iFind Real Estate to stand for trust, integrity, professionalism, and commitment — so that when clients, investors, developers, landowners, or partners deal with us, they know they are dealing with people who mean what they say and deliver what they promise.",
      "Our mission is not to become the biggest by chasing numbers. We believe in quality over quantity — carefully selected opportunities, meaningful relationships, exceptional service, and transactions built around genuine value.",
      "We are equally committed to building a different kind of real estate ecosystem from within: one where every team member is respected, valued, empowered, and given the opportunity to grow. We believe that when people are treated with dignity and work with purpose, excellence naturally follows.",
      "From everyday real estate requirements to prime land, complex transactions, commercial opportunities, investment assets, and ultra-luxury properties, our purpose is to simplify the process, find solutions where others see complexity, and protect the trust placed in us.",
      "Our ambition is clear: to establish iFind Real Estate as one of the UAE’s most respected and trusted real estate companies — recognized not only for the deals we close, but for the values we refuse to compromise.",
    ],
    signoff: "iFind Real Estate — Finding Value. Building Trust.",
    valuesEyebrow: "What We Stand For",
    valuesTitle: "Our values",
    values: [
      { title: "Integrity", text: "We say what is true, even when it is not what you hoped to hear." },
      { title: "Value", text: "Every recommendation is measured against what it is genuinely worth to you." },
      { title: "Clarity", text: "Prices, fees and terms laid out plainly, with no surprises later." },
      { title: "Service", text: "Responsive, respectful and available when you need us." },
      { title: "Expertise", text: "Registered brokers with real knowledge of the Dubai and UAE market." },
    ],
    doEyebrow: "What We Do",
    doTitle: "Buy. Sell. Lease.",
  },
  teamPage: {
    title: "Our Team",
    description: "Meet the iFind Real Estate LLC team in Dubai: our Managing Director, directors, managers and property specialists.",
    eyebrow: "Our Team",
    h1: "The people behind iFind",
    lede: "A multinational team with a global perspective and deep local expertise, committed to personalised, honest service on every deal.",
    leadership: "Leadership",
    specialists: "Specialists & Support",
    readMore: "Read More",
  },
  contact: {
    title: "Contact Us",
    description: "Speak with iFind Real Estate LLC in Dubai about off-plan, ready, luxury, rentals, land, buildings and hotels.",
    eyebrow: "Contact Us",
    h1: "Let’s talk.",
    lede: "Tell us what you are looking for. A registered consultant will get back to you shortly.",
    mobile: "Mobile / WhatsApp",
    landline: "Office Landline",
    whatsapp: "WhatsApp",
    whatsappLink: "Message us on WhatsApp",
    email: "Email",
    office: "Office",
    formTitle: "Send an enquiry",
    mapTitle: "iFind Real Estate office location on Google Maps",
    openMap: "Open in Google Maps",
  },
  careers: {
    metaTitle: "Careers at iFind Real Estate | Join Our Dubai Team",
    metaDescription: "Apply for a career at iFind Real Estate LLC in Business Bay, Dubai. Send your CV for real estate consultant, sales, leasing, marketing, operations and administration roles.",
    eyebrow: "Careers",
    h1: "Build your career with iFind",
    lede: "We are always glad to meet motivated people who value honesty, clarity and service. Send us your details and CV, and our team will review your application.",
    whyEyebrow: "Why iFind",
    whyTitle: "A team built on trust",
    why: [
      { title: "Licensed Professionals", text: "Work alongside registered brokers who know the Dubai and UAE market." },
      { title: "Honest Advice", text: "A culture that puts the client's real interest first." },
      { title: "Multinational Team", text: "A global perspective combined with deep local expertise." },
      { title: "Full-Service Market", text: "Off-plan, ready, luxury, rentals, land, buildings and hotels." },
    ],
    areasEyebrow: "Areas",
    areasTitle: "Who we are looking for",
    areasText: "We do not list fixed vacancies here. Choose the area you are interested in and we will contact you when there is a suitable opening.",
    formEyebrow: "Apply",
    formTitle: "Send your application",
    formText: "Complete the form and attach your CV. Fields marked * are required.",
    sectionPersonal: "Personal details",
    sectionProfessional: "Professional details",
    sectionDocuments: "Documents",
    fullName: "Full name *",
    email: "Email address *",
    phone: "Phone / WhatsApp *",
    nationality: "Nationality",
    location: "Current city and country",
    position: "Position you are applying for *",
    positionPlaceholder: "Select a position",
    positions: [
      { value: "Real Estate Consultant", label: "Real Estate Consultant" },
      { value: "Sales Manager", label: "Sales Manager" },
      { value: "Leasing / Rentals Consultant", label: "Leasing / Rentals Consultant" },
      { value: "Digital Marketing", label: "Digital Marketing" },
      { value: "Operations / Administration", label: "Operations / Administration" },
      { value: "Accounts / Finance", label: "Accounts / Finance" },
      { value: "Public Relations Officer (PRO)", label: "Public Relations Officer (PRO)" },
      { value: "Other / Open application", label: "Other / Open application" },
    ],
    experience: "Years of experience",
    experiencePlaceholder: "Select",
    experienceOptions: [
      { value: "Fresher", label: "Fresher" },
      { value: "Less than 1 year", label: "Less than 1 year" },
      { value: "1 to 3 years", label: "1 to 3 years" },
      { value: "3 to 5 years", label: "3 to 5 years" },
      { value: "5+ years", label: "5+ years" },
    ],
    employer: "Current or last employer",
    brn: "RERA / DLD BRN (if you have one)",
    visa: "Visa status",
    visaPlaceholder: "Select",
    visaOptions: [
      { value: "UAE residence visa", label: "UAE residence visa" },
      { value: "Visit / tourist visa", label: "Visit / tourist visa" },
      { value: "Outside the UAE", label: "Outside the UAE" },
    ],
    availability: "When can you start?",
    availabilityPlaceholder: "Select",
    availabilityOptions: [
      { value: "Immediately", label: "Immediately" },
      { value: "Within 2 weeks", label: "Within 2 weeks" },
      { value: "Within 1 month", label: "Within 1 month" },
      { value: "More than 1 month", label: "More than 1 month" },
    ],
    salary: "Expected monthly salary (AED, optional)",
    languages: "Languages you speak",
    languageOptions: [
      { value: "English", label: "English" },
      { value: "Arabic", label: "Arabic" },
      { value: "Urdu", label: "Urdu" },
      { value: "Hindi", label: "Hindi" },
      { value: "Punjabi", label: "Punjabi" },
      { value: "Pashto", label: "Pashto" },
      { value: "Russian", label: "Russian" },
      { value: "Other", label: "Other" },
    ],
    linkedin: "LinkedIn profile link (optional)",
    note: "Tell us briefly about yourself and why you would like to join iFind",
    cv: "Upload your CV *",
    cvHint: "PDF, DOC or DOCX",
    coverLetter: "Cover letter (optional)",
    otherDocs: "Other documents, such as certificates (optional)",
    chooseFile: "Choose file",
    chooseFiles: "Choose files",
    noFile: "No file chosen",
    remove: "Remove",
    limits: "PDF, DOC or DOCX only. Maximum 4 MB in total for all files.",
    consent: "I agree that iFind Real Estate LLC may store and use my details to assess my application.",
    submit: "Submit Application",
    sending: "Submitting...",
    thankTitle: "Thank you for applying.",
    thankText: "We have received your application. If your profile matches an opening, our team will contact you.",
    another: "Submit another application",
    errors: {
      required: "Please complete all required fields.",
      cvMissing: "Please upload your CV.",
      fileType: "Only PDF, DOC and DOCX files are accepted.",
      fileSize: "Your files are too large. Please keep the total under 4 MB.",
      consent: "Please accept the consent statement to continue.",
      unavailable: "Online applications are temporarily unavailable. Please email your CV to {email}.",
      generic: "Something went wrong. Please try again in a moment.",
    },
  },
  servicePage: {
    whatWeDo: "What we do",
    howWeHelp: "How we help",
    ourService: "Our service",
    process: "Process",
    processTitle: "From first call to closing",
  },
  servicePages: {
    offPlan: {
      metaTitle: "Off-Plan Properties in Dubai",
      metaDescription: "Early access to off-plan launches from Dubai's leading developers, with clear guidance on payment plans and handover.",
      eyebrow: "Off-Plan",
      title: "Off-Plan Properties",
      intro: "Early access to new launches from Dubai's established developers, explained clearly before you commit.",
      heroAlt: "Villas under construction at a new Dubai development site",
      featureAlt: "High-rise towers under construction in Dubai at sunset",
      sectionTitle: "Buy early, with clear eyes",
      sectionText:
        "Off-plan can offer attractive entry points, but every project has its own payment plan, timeline and risk profile. We help you compare launches side by side and understand exactly what you are signing.",
      offers: [
        { title: "Launch Access", text: "Information on new and upcoming launches from the developers we are registered with." },
        { title: "Payment Plan Review", text: "A plain-language breakdown of instalments, milestones and handover terms." },
        { title: "Project Comparison", text: "Location, developer track record, unit mix and specification compared fairly." },
        { title: "Unit Selection", text: "Help choosing the right unit, floor and view for your goal, whether living or investing." },
        { title: "Resale and Assignment", text: "Guidance if you want to sell an off-plan unit before handover." },
        { title: "Documentation", text: "Support through reservation, SPA and registration, step by step." },
      ],
      closing: null as null | { title: string; text: string },
    },
    readyLuxury: {
      metaTitle: "Ready & Luxury Properties in Dubai",
      metaDescription: "Move-in-ready homes and prime luxury residences across Dubai: apartments, villas, townhouses and penthouses.",
      eyebrow: "Ready & Luxury",
      title: "Ready & Luxury Properties",
      intro: "From well-priced everyday homes to signature residences in Dubai's most sought-after addresses.",
      heroAlt: "Luxury waterfront villa with a pool at sunset",
      featureAlt: "Luxury interior with a glass and marble staircase",
      sectionTitle: "Find the right home, at the right value",
      sectionText:
        "Whether you want a practical apartment or a landmark penthouse, we work from your brief and show you what is genuinely worth your attention, not simply what is available.",
      offers: [
        { title: "Apartments", text: "Studios to multi-bedroom residences across Dubai's established and emerging communities." },
        { title: "Villas and Townhouses", text: "Family homes with space, privacy and strong community amenities." },
        { title: "Luxury Residences", text: "Prime penthouses, branded residences and waterfront homes at the top end of the market." },
        { title: "Private Viewings", text: "Scheduled around you, with honest feedback on each property." },
        { title: "Price Guidance", text: "Comparable-based advice so you buy and sell with confidence." },
        { title: "Selling Your Property", text: "Positioning, pricing and presentation to reach serious buyers." },
      ],
      closing: null as null | { title: string; text: string },
    },
    rentals: {
      metaTitle: "Rentals & Leasing in Dubai",
      metaDescription: "Residential and commercial leasing for tenants and landlords in Dubai and across the UAE.",
      eyebrow: "Rentals & Leasing",
      title: "Rentals & Leasing",
      intro: "Residential and commercial leasing for tenants and landlords, handled with clarity and discretion.",
      heroAlt: "Modern residence with a terrace and pool",
      featureAlt: "Terrace lounge of a modern Dubai home",
      sectionTitle: "The right tenant. The right place.",
      sectionText:
        "We connect landlords with reliable tenants and tenants with properties that suit their needs and budget, and we keep the process straightforward from viewing to signing.",
      offers: [
        { title: "For Tenants", text: "A focused shortlist matched to your budget, location and lifestyle." },
        { title: "For Landlords", text: "Marketing, viewings and tenant screening to place your property well." },
        { title: "Commercial Leasing", text: "Offices, retail units, warehouses and other commercial spaces." },
        { title: "Rental Guidance", text: "Realistic rent expectations based on current comparable listings." },
        { title: "Tenancy Paperwork", text: "Support with contracts and registration so everything is in order." },
        { title: "Long and Short Term", text: "Options to suit different lease lengths and requirements." },
      ],
      closing: null as null | { title: string; text: string },
    },
    land: {
      metaTitle: "Land, Buildings & Hotels in the UAE",
      metaDescription: "Buy and sell plots, enter joint ventures and complete complex deals across the UAE, including warehouses, buildings and hotels.",
      eyebrow: "Land, Buildings & Hotels",
      title: "Land, Buildings & Hotels",
      intro: "Plots, joint ventures and complex commercial deals across the UAE, including opportunities beyond it.",
      heroAlt: "Dubai skyline at sunset",
      featureAlt: "High-rise balcony with a view of the Burj Khalifa",
      sectionTitle: "Complex deals, handled with experience",
      sectionText:
        "Land and large assets need careful structuring. We work on single plots and multiple plots, joint ventures, and transactions involving warehouses, buildings and hotels. We source, evaluate and negotiate on your behalf.",
      offers: [
        { title: "Plot Sales and Purchases", text: "Residential, commercial and mixed-use land across the UAE." },
        { title: "Multiple Plots", text: "Assembling or selling several plots together as a single transaction." },
        { title: "Joint Ventures", text: "Introductions and deal structuring between landowners and developers." },
        { title: "Buildings", text: "Whole-building acquisitions and sales for investors and end users." },
        { title: "Hotels and Hospitality", text: "Hotel and hospitality assets for qualified buyers and sellers." },
        { title: "Warehouses", text: "Industrial and logistics properties for sale or lease." },
      ],
      sections: [
        {
          eyebrow: "Buildings",
          title: "Whole buildings, bought and sold with care",
          text: "Buildings are significant assets and need careful evaluation. We handle whole-building acquisitions and sales for investors and end users, from first introduction to completion.",
          points: [
            { title: "Whole-Building Acquisitions", text: "Sourcing and evaluating buildings that match your brief." },
            { title: "Building Sales", text: "Positioning and negotiation for owners who want to sell." },
            { title: "Warehouses", text: "Industrial and logistics properties for sale or lease." },
          ],
          alts: ["Waterfront high-rise towers in Dubai under a blue sky", "Dubai high-rise skyline with the Burj Khalifa"],
        },
        {
          eyebrow: "Hotels",
          title: "Hotels and hospitality assets",
          text: "Hotel and hospitality assets for qualified buyers and sellers. We approach each opportunity with discretion, and tell you honestly what we can and cannot do.",
          points: [
            { title: "Hotels and Hospitality", text: "Hotel and hospitality assets for qualified buyers and sellers." },
            { title: "Discreet Handling", text: "Confidential introductions and careful communication." },
          ],
          alts: ["Luxury hotel entrance with fountains at dusk"],
        },
        {
          eyebrow: "Land",
          title: "Plots and land across the UAE",
          text: "Land needs careful structuring. We work on single plots and multiple plots, and on joint ventures between landowners and developers.",
          points: [
            { title: "Plot Sales and Purchases", text: "Residential, commercial and mixed-use land across the UAE." },
            { title: "Multiple Plots", text: "Assembling or selling several plots together as a single transaction." },
            { title: "Joint Ventures", text: "Introductions and deal structuring between landowners and developers." },
          ],
          alts: ["Open plots of land in Dubai with the city skyline behind", "Aerial map view of a master-planned plot area"],
        },
      ],
      closing: {
        title: "Looking outside the UAE?",
        text: "We can also discuss land opportunities beyond the UAE. Tell us what you are looking for and we will let you know honestly what we can do.",
      } as null | { title: string; text: string },
    },
    investors: {
      metaTitle: "Investor Services",
      metaDescription: "Investment opportunities in Dubai and the UAE for local and international investors: off-plan, ready, land, buildings and hotels.",
      eyebrow: "Investor Services",
      title: "Investor Services",
      intro: "Finding, evaluating and closing real estate investments in Dubai and across the UAE, for local and international investors.",
      featureAlt: "A consultant advising an investor in a Dubai office with a view of the skyline",
      sectionTitle: "Invest with clarity, not guesswork",
      sectionText:
        "We help you identify opportunities that match your capital and goals, explain the numbers plainly, and carry the deal through to completion. We do not promise returns. We give you the facts so you can decide.",
      offers: [
        { title: "Opportunity Sourcing", text: "Off-plan, ready, land and commercial opportunities matched to your brief." },
        { title: "Market Briefing", text: "Honest context on areas, pricing and demand before you commit." },
        { title: "Deal Evaluation", text: "Costs, fees, payment terms and exit options laid out clearly." },
        { title: "Large and Complex Deals", text: "Multiple plots, joint ventures, buildings, warehouses and hotels." },
        { title: "International Investors", text: "Remote-friendly communication and guidance on the buying process in the UAE." },
        { title: "Selling and Leasing", text: "Support when you want to sell or lease an asset you already own." },
      ],
      closing: null as null | { title: string; text: string },
    },
  },
  privacy: {
    metaTitle: "Privacy Policy | iFind Real Estate LLC, Dubai",
    metaDescription: "How iFind Real Estate LLC in Dubai collects, uses, shares and protects your personal data, and the rights you have under UAE data protection law.",
    eyebrow: "Legal",
    h1: "Privacy Policy",
    lede: "Your trust matters to us. This policy explains in plain language how we handle your personal data.",
    updated: "Last updated: October 2026",
    onThisPage: "On this page",
    contactCard: "Data enquiries",
    sections: [
      {
        title: "Who we are",
        body: [
          "iFind Real Estate LLC (\u201ciFind\u201d, \u201cwe\u201d, \u201cus\u201d) is a real estate brokerage located at Office No. 1810, Churchill Tower, Business Bay, Dubai, United Arab Emirates (ORN: 45937). We are responsible for the personal data we collect through this website and through our communications with you.",
          "This policy explains what personal data we collect, why we use it, who we share it with, how long we keep it and the rights you have. It is written to align with UAE Federal Decree-Law No. 45 of 2021 on the Protection of Personal Data and the other laws that apply to our business in Dubai.",
        ],
        list: [] as string[],
      },
      {
        title: "Personal data we collect",
        body: ["We collect only what we need, depending on how you deal with us:"],
        list: [
          "Enquiries: your name, phone or WhatsApp number, email address, the service you are interested in and any message you send through our contact form or chat.",
          "Job applications: the details you enter in the careers form, such as nationality, current location, experience, visa status, languages and BRN, together with your CV and any documents you upload.",
          "Communications: records of calls, WhatsApp messages and emails with our team, so that we can follow up on your request.",
          "Technical data: information your browser sends automatically, such as IP address, device and browser type and the pages visited, which is recorded in our hosting provider's server logs for security and reliability.",
        ],
        after: "We do not ask for payment card details, passwords or Emirates ID copies through this website.",
      },
      {
        title: "How and why we use your data",
        body: [],
        list: [
          "To respond to your enquiries and contact you about the properties and services you asked about.",
          "To provide our brokerage services, such as buying, selling and leasing, and to carry out the steps you ask us to take.",
          "To assess job applications and contact applicants.",
          "To meet legal and regulatory duties that apply to real estate brokers in the UAE, including anti-money laundering and customer due diligence requirements, and requests from competent authorities.",
          "To keep the website secure, prevent misuse and improve its performance.",
          "To send you marketing messages, only where you have agreed to receive them.",
        ],
        after: "Where the law requires it, we rely on your consent. Other grounds we may rely on include performing a contract or taking steps at your request, complying with a legal obligation, and our legitimate interests in running and protecting our business, always balanced against your rights.",
      },
      {
        title: "Cookies and similar technologies",
        body: [
          "This website does not currently use advertising or tracking cookies. Our chat window may store a small note in your browser session so that it does not greet you repeatedly. If we add analytics or marketing tools in the future, we will ask for your consent where required and update this policy.",
          "The map on our Contact page is provided by Google Maps. When it loads, Google may receive technical data and set its own cookies, under Google's privacy policy.",
        ],
        list: [] as string[],
      },
      {
        title: "Who we share data with",
        body: ["We do not sell your personal data. We share it only where needed, and only with:"],
        list: [
          "Our team members and consultants who deal with your request.",
          "Property developers, banks and other parties directly involved in a transaction you decide to proceed with.",
          "Service providers that support us, such as website hosting, email delivery and communication tools, who may process data only on our instructions.",
          "Government and regulatory bodies, such as the Dubai Land Department and the Real Estate Regulatory Agency, and law-enforcement or judicial authorities, when we are required by law.",
        ],
        after: "If you choose to contact us through WhatsApp, your messages are also handled by WhatsApp under its own terms.",
      },
      {
        title: "Transfers outside the UAE",
        body: ["Some of our service providers may store or process data on servers outside the UAE. Where this happens, we take steps to make sure your data stays protected, in line with applicable UAE law."],
        list: [] as string[],
      },
      {
        title: "How long we keep your data",
        body: ["We keep personal data only for as long as needed for the purpose it was collected for, to meet legal and record-keeping duties that apply to real estate brokers, and to handle any claims. Job applications are kept for a limited period for recruitment and are then deleted, unless you ask us to keep them for future openings. When data is no longer needed, we delete or anonymise it."],
        list: [] as string[],
      },
      {
        title: "How we protect your data",
        body: ["We use reasonable technical and organisational measures to protect personal data against loss, misuse and unauthorised access, including encrypted connections (HTTPS), access limited to staff who need it, and checks on the service providers we use. No online system is completely secure, so please avoid sending sensitive documents unless we have asked for them."],
        list: [] as string[],
      },
      {
        title: "Your rights",
        body: ["Under UAE data protection law you may have the right to:"],
        list: [
          "Know what personal data we hold about you and obtain a copy.",
          "Ask us to correct data that is inaccurate or incomplete.",
          "Ask us to delete your data or restrict how we use it, where the law allows.",
          "Object to the use of your data for marketing, or withdraw a consent you gave earlier.",
          "Request that your data be transferred to another provider, where applicable.",
        ],
        after: "To use any of these rights, contact us using the details below. We may need to confirm your identity first, and we will reply within the period required by law. You also have the right to complain to the UAE Data Office if you believe your data has been mishandled.",
      },
      {
        title: "Marketing messages",
        body: ["We contact people about our services by phone, WhatsApp, email or SMS only in line with UAE law, and where you have given consent or asked us to. You can opt out at any time by replying STOP, using the unsubscribe link or telling us directly, and we will then stop sending marketing messages."],
        list: [] as string[],
      },
      {
        title: "Children",
        body: ["This website is intended for adults. We do not knowingly collect personal data from anyone under 18. If you think a child has given us personal data, please contact us and we will delete it."],
        list: [] as string[],
      },
      {
        title: "Links to other websites",
        body: ["Our website links to other sites, including the official websites of developers and our social media pages. We are not responsible for their content or privacy practices, so please read their policies."],
        list: [] as string[],
      },
      {
        title: "Changes to this policy",
        body: ["We may update this policy from time to time. The latest version is always on this page, with the date of the last update shown at the top."],
        list: [] as string[],
      },
      {
        title: "Contact us",
        body: ["For any question about this policy or your personal data, please contact us:"],
        list: [] as string[],
      },
    ],
  },
  legal: {
    eyebrow: "Legal",
    privacyTitle: "Privacy Policy",
    termsTitle: "Terms of Use",
    placeholder: "This page is a placeholder. The final {doc} for {company} will be published here.",
  },
};

export type Dict = typeof en;
